package engine

// W-T3 — cross-runtime SEMANTIC agreement gate (ticket 20260709).
//
// The golden-keys fixture pins the KEY SHAPES both runtimes write; this pins
// the BOUNDARY SEMANTICS: double release, unknown-id release, settle/release
// orderings, acquire at/over the limit, floors, magnitude deltas, concurrent
// release of one id. Expectations come from
// testdata/golden_semantics_python_20260710.json, generated by EXECUTING the
// Python reference (dump_golden_semantics_python.py, fakeredis) — never by
// reading it. A single silent disagreement here means a mixed Python/Go fleet
// sharing one keyspace diverges in production with no error anywhere.
//
// Emulator caveat: Go side runs on miniredis (gopher-lua); the Python side of
// the fixture ran on fakeredis (lupa). This gate therefore proves EMULATOR-
// level agreement; real-Redis behaviour for both lanes is the standing
// pre-deploy gate (V-BATCH blocker A1).

import (
	"context"
	"encoding/json"
	"os"
	"sync"
	"testing"

	"github.com/alicebob/miniredis/v2"
	"github.com/redis/go-redis/v9"

	"github.com/ab0t-com/ab0t-quota-go/activations"
	"github.com/ab0t-com/ab0t-quota-go/counters"
)

type goldenSemantics struct {
	AcquireAtLimit struct {
		Admitted           []bool  `json:"admitted"`
		ActivationIDMinted []bool  `json:"activation_id_minted"`
		Gauge              float64 `json:"gauge"`
	} `json:"acquire_at_limit"`
	ConcurrentReleaseOneID struct {
		Gauge          float64 `json:"gauge"`
		PerformedCount int     `json:"performed_count"`
	} `json:"concurrent_release_one_id"`
	DoubleRelease struct {
		FirstPerformed   bool    `json:"first_performed"`
		SecondPerformed  bool    `json:"second_performed"`
		GaugeAfterFirst  float64 `json:"gauge_after_first"`
		GaugeAfterSecond float64 `json:"gauge_after_second"`
	} `json:"double_release"`
	DuplicateAcquireSameIdem struct {
		First struct {
			Admitted           bool   `json:"admitted"`
			Reason             string `json:"reason"`
			ActivationIDMinted bool   `json:"activation_id_minted"`
		} `json:"first"`
		Replay struct {
			Admitted           bool   `json:"admitted"`
			Reason             string `json:"reason"`
			ActivationIDMinted bool   `json:"activation_id_minted"`
		} `json:"replay"`
		Gauge float64 `json:"gauge"`
	} `json:"duplicate_acquire_same_idem"`
	LegacyFloor struct {
		Decrement5From1 float64 `json:"decrement_5_from_1"`
		DecrementAtZero float64 `json:"decrement_at_zero"`
	} `json:"legacy_floor"`
	LegacyNegativeDeltaMagnitude struct {
		IncrementMinus3From5 float64 `json:"increment_minus3_from_5"`
		DecrementMinus2After float64 `json:"decrement_minus2_after"`
	} `json:"legacy_negative_delta_magnitude"`
	PerUserAcquireRelease struct {
		Admitted              bool     `json:"admitted"`
		UserGaugeAfterAcquire float64  `json:"user_gauge_after_acquire"`
		SeqAfterAcquire       *float64 `json:"seq_after_acquire"`
		ReleasePerformed      bool     `json:"release_performed"`
		OrgGaugeAfterRelease  float64  `json:"org_gauge_after_release"`
		UserGaugeAfterRelease float64  `json:"user_gauge_after_release"`
	} `json:"per_user_acquire_release"`
	ReleaseUnknownID struct {
		Gauge     float64 `json:"gauge"`
		Performed bool    `json:"performed"`
	} `json:"release_unknown_id"`
	SettleAfterRelease struct {
		Gauge        float64 `json:"gauge"`
		Released     bool    `json:"released"`
		Settled      bool    `json:"settled"`
		SettleReplay bool    `json:"settle_replay"`
	} `json:"settle_after_release"`
	SettleWithoutRelease struct {
		Settled                     bool    `json:"settled"`
		GaugeAfterSettle            float64 `json:"gauge_after_settle"`
		ReleaseAfterSettlePerformed bool    `json:"release_after_settle_performed"`
		GaugeAfterReleaseAttempt    float64 `json:"gauge_after_release_attempt"`
	} `json:"settle_without_release"`
}

func loadGoldenSemantics(t *testing.T) goldenSemantics {
	t.Helper()
	raw, err := os.ReadFile("testdata/golden_semantics_python_20260710.json")
	if err != nil {
		t.Fatalf("golden semantics fixture missing (regenerate with "+
			"dump_golden_semantics_python.py): %v", err)
	}
	var g goldenSemantics
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	return g
}

// semEnv builds a fresh miniredis-backed engine (Redis counters + Redis
// activation store — the mixed-fleet configuration D-22 cares about).
func semEnv(t *testing.T, limit float64) (*Engine, *counters.Factory) {
	t.Helper()
	mr := miniredis.RunT(t)
	client := redis.NewClient(&redis.Options{Addr: mr.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	fs, err := counters.NewRedisFactory(client, "quota")
	if err != nil {
		t.Fatal(err)
	}
	store := activations.NewRedisStore(client, "", 0)
	return activationEngine(t, fs, store, limit), fs
}

func gaugeVal(t *testing.T, fs *counters.Factory, key string) float64 {
	t.Helper()
	v, _, err := fs.Floats.GetFloat(context.Background(), key)
	if err != nil {
		t.Fatal(err)
	}
	return v
}

func TestGoldenSemantics_CrossRuntimeAgreement_WT3(t *testing.T) {
	golden := loadGoldenSemantics(t)
	ctx := context.Background()
	g := counters.Gauge{Prefix: "quota", ResourceKey: "sandboxes"}
	orgKey := g.OrgKey("o1")

	t.Run("acquire_at_limit_and_limit_plus_one", func(t *testing.T) {
		e, fs := semEnv(t, 2)
		var admitted, minted []bool
		for i := 0; i < 3; i++ {
			res, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"})
			if err != nil {
				t.Fatal(err)
			}
			admitted = append(admitted, res.Admitted)
			minted = append(minted, res.ActivationID != "")
		}
		for i := range admitted {
			if admitted[i] != golden.AcquireAtLimit.Admitted[i] {
				t.Errorf("DIVERGENCE acquire #%d: Go admitted=%v, Python=%v",
					i+1, admitted[i], golden.AcquireAtLimit.Admitted[i])
			}
			if minted[i] != golden.AcquireAtLimit.ActivationIDMinted[i] {
				t.Errorf("DIVERGENCE acquire #%d: Go minted=%v, Python=%v",
					i+1, minted[i], golden.AcquireAtLimit.ActivationIDMinted[i])
			}
		}
		if v := gaugeVal(t, fs, orgKey); v != golden.AcquireAtLimit.Gauge {
			t.Errorf("DIVERGENCE gauge after at-limit sequence: Go=%v Python=%v",
				v, golden.AcquireAtLimit.Gauge)
		}
	})

	t.Run("double_release", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		res, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"})
		if err != nil || !res.Admitted {
			t.Fatalf("acquire: %+v %v", res, err)
		}
		first, err := e.ReleaseActivation(ctx, res.ActivationID)
		if err != nil {
			t.Fatal(err)
		}
		gaugeFirst := gaugeVal(t, fs, orgKey)
		second, err := e.ReleaseActivation(ctx, res.ActivationID)
		if err != nil {
			t.Fatal(err)
		}
		gd := golden.DoubleRelease
		if first != gd.FirstPerformed || second != gd.SecondPerformed ||
			gaugeFirst != gd.GaugeAfterFirst || gaugeVal(t, fs, orgKey) != gd.GaugeAfterSecond {
			t.Errorf("DIVERGENCE double_release: Go(first=%v second=%v g1=%v g2=%v) Python(%+v)",
				first, second, gaugeFirst, gaugeVal(t, fs, orgKey), gd)
		}
	})

	t.Run("release_unknown_id", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		if _, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"}); err != nil {
			t.Fatal(err)
		}
		performed, err := e.ReleaseActivation(ctx, "act_00000000000000000000000000000000")
		if err != nil {
			t.Fatal(err)
		}
		if performed != golden.ReleaseUnknownID.Performed ||
			gaugeVal(t, fs, orgKey) != golden.ReleaseUnknownID.Gauge {
			t.Errorf("DIVERGENCE release_unknown_id: Go(performed=%v gauge=%v) Python(%+v)",
				performed, gaugeVal(t, fs, orgKey), golden.ReleaseUnknownID)
		}
	})

	t.Run("settle_without_release_strands_the_spend", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		res, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"})
		if err != nil {
			t.Fatal(err)
		}
		settled, err := e.Settle(ctx, res.ActivationID, "0.42")
		if err != nil {
			t.Fatal(err)
		}
		gaugeAfterSettle := gaugeVal(t, fs, orgKey)
		released, err := e.ReleaseActivation(ctx, res.ActivationID)
		if err != nil {
			t.Fatal(err)
		}
		gw := golden.SettleWithoutRelease
		if settled != gw.Settled || gaugeAfterSettle != gw.GaugeAfterSettle ||
			released != gw.ReleaseAfterSettlePerformed ||
			gaugeVal(t, fs, orgKey) != gw.GaugeAfterReleaseAttempt {
			t.Errorf("DIVERGENCE settle_without_release: Go(settled=%v g=%v released=%v g2=%v) Python(%+v)",
				settled, gaugeAfterSettle, released, gaugeVal(t, fs, orgKey), gw)
		}
	})

	t.Run("settle_after_release", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		res, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"})
		if err != nil {
			t.Fatal(err)
		}
		released, _ := e.ReleaseActivation(ctx, res.ActivationID)
		settled, _ := e.Settle(ctx, res.ActivationID, "1.00")
		replay, _ := e.Settle(ctx, res.ActivationID, "9.99")
		sa := golden.SettleAfterRelease
		if released != sa.Released || settled != sa.Settled || replay != sa.SettleReplay ||
			gaugeVal(t, fs, orgKey) != sa.Gauge {
			t.Errorf("DIVERGENCE settle_after_release: Go(released=%v settled=%v replay=%v gauge=%v) Python(%+v)",
				released, settled, replay, gaugeVal(t, fs, orgKey), sa)
		}
	})

	t.Run("concurrent_release_one_id", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		a1, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"})
		if err != nil {
			t.Fatal(err)
		}
		if _, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes"}); err != nil {
			t.Fatal(err)
		}
		var mu sync.Mutex
		performed := 0
		var wg sync.WaitGroup
		for i := 0; i < 10; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				ok, err := e.ReleaseActivation(ctx, a1.ActivationID)
				if err != nil {
					t.Error(err)
					return
				}
				if ok {
					mu.Lock()
					performed++
					mu.Unlock()
				}
			}()
		}
		wg.Wait()
		cr := golden.ConcurrentReleaseOneID
		if performed != cr.PerformedCount || gaugeVal(t, fs, orgKey) != cr.Gauge {
			t.Errorf("DIVERGENCE concurrent_release: Go(performed=%d gauge=%v) Python(%+v)",
				performed, gaugeVal(t, fs, orgKey), cr)
		}
	})

	t.Run("duplicate_acquire_same_idem", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		r1, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes", IdempotencyKey: "create-1"})
		if err != nil {
			t.Fatal(err)
		}
		r2, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", ResourceKey: "sandboxes", IdempotencyKey: "create-1"})
		if err != nil {
			t.Fatal(err)
		}
		da := golden.DuplicateAcquireSameIdem
		if r1.Admitted != da.First.Admitted || r1.Reason != da.First.Reason ||
			(r1.ActivationID != "") != da.First.ActivationIDMinted {
			t.Errorf("DIVERGENCE dup-acquire first: Go(%+v) Python(%+v)", r1, da.First)
		}
		if r2.Admitted != da.Replay.Admitted || r2.Reason != da.Replay.Reason ||
			(r2.ActivationID != "") != da.Replay.ActivationIDMinted {
			t.Errorf("DIVERGENCE dup-acquire replay: Go(admitted=%v reason=%q minted=%v) Python(%+v)",
				r2.Admitted, r2.Reason, r2.ActivationID != "", da.Replay)
		}
		if gaugeVal(t, fs, orgKey) != da.Gauge {
			t.Errorf("DIVERGENCE dup-acquire gauge: Go=%v Python=%v", gaugeVal(t, fs, orgKey), da.Gauge)
		}
	})

	t.Run("legacy_floor", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		if _, err := e.Spend(ctx, CheckInput{OrgID: "o1", ResourceKey: "sandboxes", Cost: 1}); err != nil {
			t.Fatal(err)
		}
		if err := e.Release(ctx, CheckInput{OrgID: "o1", ResourceKey: "sandboxes", Cost: 5}); err != nil {
			t.Fatal(err)
		}
		lf := golden.LegacyFloor
		if v := gaugeVal(t, fs, orgKey); v != lf.Decrement5From1 {
			t.Errorf("DIVERGENCE legacy floor: Go gauge=%v Python=%v", v, lf.Decrement5From1)
		}
		if err := e.Release(ctx, CheckInput{OrgID: "o1", ResourceKey: "sandboxes", Cost: 1}); err != nil {
			t.Fatal(err)
		}
		if v := gaugeVal(t, fs, orgKey); v != lf.DecrementAtZero {
			t.Errorf("DIVERGENCE release at zero: Go gauge=%v Python=%v", v, lf.DecrementAtZero)
		}
	})

	t.Run("legacy_negative_delta_magnitude", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		if err := fs.Floats.Set(ctx, orgKey, 5, 0); err != nil {
			t.Fatal(err)
		}
		vInc, err := e.Spend(ctx, CheckInput{OrgID: "o1", ResourceKey: "sandboxes", Cost: -3})
		if err != nil {
			t.Fatal(err)
		}
		lm := golden.LegacyNegativeDeltaMagnitude
		if vInc != lm.IncrementMinus3From5 {
			t.Errorf("DIVERGENCE Spend(-3) from 5: Go=%v Python=%v", vInc, lm.IncrementMinus3From5)
		}
		if err := e.Release(ctx, CheckInput{OrgID: "o1", ResourceKey: "sandboxes", Cost: -2}); err != nil {
			t.Fatal(err)
		}
		if v := gaugeVal(t, fs, orgKey); v != lm.DecrementMinus2After {
			t.Errorf("DIVERGENCE Release(-2): Go gauge=%v Python=%v", v, lm.DecrementMinus2After)
		}
	})

	t.Run("per_user_acquire_release", func(t *testing.T) {
		e, fs := semEnv(t, 10)
		res, err := e.Acquire(ctx, AcquireInput{OrgID: "o1", UserID: "user-1", ResourceKey: "sandboxes"})
		if err != nil {
			t.Fatal(err)
		}
		pu := golden.PerUserAcquireRelease
		if res.Admitted != pu.Admitted {
			t.Errorf("DIVERGENCE per-user admit: Go=%v Python=%v", res.Admitted, pu.Admitted)
		}
		userKey := g.UserKey("o1", "user-1")
		seqKey := g.UserSeqKey("o1", "user-1")
		if v := gaugeVal(t, fs, userKey); v != pu.UserGaugeAfterAcquire {
			t.Errorf("DIVERGENCE user gauge after acquire: Go=%v Python=%v", v, pu.UserGaugeAfterAcquire)
		}
		if pu.SeqAfterAcquire != nil {
			if v := gaugeVal(t, fs, seqKey); v != *pu.SeqAfterAcquire {
				t.Errorf("DIVERGENCE seq after acquire: Go=%v Python=%v", v, *pu.SeqAfterAcquire)
			}
		}
		performed, err := e.ReleaseActivation(ctx, res.ActivationID)
		if err != nil {
			t.Fatal(err)
		}
		if performed != pu.ReleasePerformed ||
			gaugeVal(t, fs, orgKey) != pu.OrgGaugeAfterRelease ||
			gaugeVal(t, fs, userKey) != pu.UserGaugeAfterRelease {
			t.Errorf("DIVERGENCE per-user release: Go(performed=%v org=%v user=%v) Python(%+v)",
				performed, gaugeVal(t, fs, orgKey), gaugeVal(t, fs, userKey), pu)
		}
	})
}
