// Package conformance is the GO runner of the shared cross-runtime
// conformance suite (D-43), ticket 20260709_ab0t_quota_systemic_integrity_
// redesign (W-CONF, 2026-07-11).
//
// One data file, two thin runners. scenarios.json is generated by EXECUTING
// the Python reference (shared/ab0t-quota/conformance/generate_scenarios.py —
// the golden-key standard, D-58): every expectation in it is an executed
// observation, never a hand-written number. This runner replays the SAME
// file against the Go engine; the Python runner
// (shared/ab0t-quota/tests/test_conformance_suite_20260711.py) replays it
// against Python. A change to either runtime that breaks parity fails CI on
// the same JSON row in both languages.
//
// The fixture folds in the D-48 enforcement matrix and the D-58
// golden-semantics set; the per-runtime originals (enforcement_matrix_d48_
// test.go, golden_semantics_parity_wt3_test.go) REMAIN — this suite is
// additive (the D-18/D-20 rule: never rewrite a peer's test).
//
// KNOWN DIVERGENCES (the D-54 pattern): a row where Go intentionally-or-
// pending-fix differs carries `expect_go` / `expect_events_go` overrides plus
// a `known_divergences` register entry with decision refs. This runner
// asserts the override where present — so the delta is DOCUMENTED, machine-
// pinned to Go's current behaviour (a Go change that moves the delta still
// fails), and never silently blessed into the shared contract. Removing the
// override the moment Go aligns turns the row back into a hard parity gate.
//
// The canonical scenarios.json lives in the PYTHON repo (the reference);
// this directory holds the synced copy. TestScenariosFileInSyncWithCanonical
// byte-compares the two whenever the canonical path is visible, so a stale
// copy is a test failure, not a silent fork.
//
// Emulator caveat (D-57): Go replays on miniredis (gopher-lua); the fixture
// was generated on fakeredis (lupa). The suite pins EMULATOR-level
// agreement; real Redis for both lanes is the standing pre-deploy gate.
package conformance

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sync"
	"testing"
	"time"

	"github.com/alicebob/miniredis/v2"
	"github.com/redis/go-redis/v9"

	"github.com/ab0t-com/ab0t-quota-go/activations"
	"github.com/ab0t-com/ab0t-quota-go/config"
	"github.com/ab0t-com/ab0t-quota-go/counters"
	"github.com/ab0t-com/ab0t-quota-go/engine"
	"github.com/ab0t-com/ab0t-quota-go/messages"
	"github.com/ab0t-com/ab0t-quota-go/providers"
	"github.com/ab0t-com/ab0t-quota-go/reconcile"
	"github.com/ab0t-com/ab0t-quota-go/registry"
)

const (
	org           = "conf-org"
	tierID        = "conf_tier"
	canonicalPath = "/home/ubuntu/infra/infra/code/shared/ab0t-quota/conformance/scenarios.json"
)

// ---------------------------------------------------------------------------
// fixture schema (mirrors generate_scenarios.py's emitted JSON)
// ---------------------------------------------------------------------------

type resDefJSON struct {
	Key           string `json:"key"`
	CounterType   string `json:"counter_type"`
	WindowSeconds int    `json:"window_seconds"`
}

type reconcileCfgJSON struct {
	ActivityGuardSeconds int `json:"activity_guard_seconds"`
}

type cfgJSON struct {
	Resources   []resDefJSON        `json:"resources"`
	Limits      map[string]float64  `json:"limits"`
	OrgTier     string              `json:"org_tier"`
	Bundles     map[string][]string `json:"bundles"`
	Enforcement map[string]any      `json:"enforcement"`
	Reconcile   *reconcileCfgJSON   `json:"reconcile"`
}

type setupJSON struct {
	Do         string         `json:"do"`
	Resource   string         `json:"resource"`
	Value      float64        `json:"value"`
	N          int            `json:"n"`
	AgeSeconds int            `json:"age_seconds"`
	Observed   map[string]int `json:"observed"`
	Type       string         `json:"type"`
}

type opJSON struct {
	Op       string         `json:"op"`
	Resource string         `json:"resource"`
	Bundle   string         `json:"bundle"`
	User     string         `json:"user"`
	Idem     string         `json:"idem"`
	Save     string         `json:"save"`
	Ref      string         `json:"ref"`
	ID       string         `json:"id"`
	Cost     string         `json:"cost"`
	Delta    float64        `json:"delta"`
	N        int            `json:"n"`
	Value    float64        `json:"value"`
	Scope    string         `json:"scope"`
	Expect   map[string]any `json:"expect"`
	ExpectGo map[string]any `json:"expect_go"` // known_divergence override
}

type eventJSON struct {
	Kind     string `json:"kind"`
	Resource string `json:"resource"`
}

type targetJSON struct {
	Resource string `json:"resource"`
	Bundle   string `json:"bundle"`
}

type scenarioJSON struct {
	ID             string         `json:"id"`
	Kind           string         `json:"kind"`
	Group          string         `json:"group"`
	DecisionRefs   []string       `json:"decision_refs"`
	Config         cfgJSON        `json:"config"`
	Setup          []setupJSON    `json:"setup"`
	Gates          []string       `json:"gates"`
	Expect         map[string]any `json:"expect"`
	ExpectGoRow    map[string]any `json:"expect_go"` // known_divergence override (gate_matrix rows)
	Target         *targetJSON    `json:"target"`
	Ops            []opJSON       `json:"ops"`
	ExpectEvents   []eventJSON    `json:"expect_events"`
	ExpectEventsGo *[]eventJSON   `json:"expect_events_go"` // nil = no override
}

type fixtureJSON struct {
	ConformanceVersion string           `json:"conformance_version"`
	KnownDivergences   []map[string]any `json:"known_divergences"`
	Scenarios          []scenarioJSON   `json:"scenarios"`
}

func loadFixture(t *testing.T) fixtureJSON {
	t.Helper()
	raw, err := os.ReadFile("scenarios.json")
	if err != nil {
		t.Fatalf("conformance fixture missing (sync it from the canonical copy: "+
			"cp %s ./scenarios.json): %v", canonicalPath, err)
	}
	var f fixtureJSON
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatal(err)
	}
	if f.ConformanceVersion != "1" {
		t.Fatalf("conformance_version %q not supported by this runner", f.ConformanceVersion)
	}
	return f
}

// ---------------------------------------------------------------------------
// the Go environment for one scenario
// ---------------------------------------------------------------------------

// putFailsStore injects the crash between the atomic spend and the persist
// (the D-27/D-28/D-31 fail-direction row).
type putFailsStore struct{ activations.Store }

func (putFailsStore) PutOpen(context.Context, activations.Activation) error {
	return errors.New("injected: activation store unavailable")
}

// durableStore lets the reconciler run against the test store (its D-37/D-39
// refuse-gate is covered by the Go reconciler's own suite; here we test the
// precedence LAW, which the fixture encodes).
type durableStore struct{ activations.Store }

func (durableStore) Durable() bool { return true }

type env struct {
	eng      *engine.Engine
	fs       *counters.Factory
	store    activations.Store
	handles  map[string]string
	events   []eventJSON
	provider reconcile.ObservedUsageProvider
	guardSec int
	clock    func() time.Time
}

func boolKnob(m map[string]any, key string, def bool) bool {
	if m == nil {
		return def
	}
	if v, ok := m[key]; ok {
		b, _ := v.(bool)
		return b
	}
	return def
}

func newEnv(t *testing.T, sc scenarioJSON) *env {
	t.Helper()
	mr := miniredis.RunT(t)
	client := redis.NewClient(&redis.Options{Addr: mr.Addr()})
	t.Cleanup(func() { _ = client.Close() })
	fs, err := counters.NewRedisFactory(client, "quota")
	if err != nil {
		t.Fatal(err)
	}

	var resources []config.ResourceDef
	for _, r := range sc.Config.Resources {
		resources = append(resources, config.ResourceDef{
			Service: "conf", ResourceKey: r.Key, DisplayName: r.Key,
			CounterType: config.CounterType(r.CounterType), Unit: "u",
			WindowSeconds: r.WindowSeconds,
		})
	}
	limits := map[string]config.TierLimit{}
	for k, v := range sc.Config.Limits {
		lv := v
		limits[k] = config.TierLimit{Limit: &lv}
	}
	orgTier := sc.Config.OrgTier
	if orgTier == "" {
		orgTier = tierID
	}
	cfg := &config.Config{
		// Enforcement: Python's EnforcementConfig defaults enabled=true; the
		// fragment only carries explicit knobs, so absent == true here too.
		Enforcement: config.EnforcementConfig{
			Enabled:          boolKnob(sc.Config.Enforcement, "enabled", true),
			ShadowMode:       boolKnob(sc.Config.Enforcement, "shadow_mode", false),
			GlobalKillSwitch: boolKnob(sc.Config.Enforcement, "global_kill_switch", false),
		},
		TierProvider:    config.TierProviderConfig{Type: "static", DefaultTier: orgTier},
		Tiers:           []config.Tier{{TierID: tierID, Limits: limits}},
		Resources:       resources,
		ResourceBundles: sc.Config.Bundles,
	}
	prov, err := providers.New(cfg.TierProvider)
	if err != nil {
		t.Fatal(err)
	}

	var store activations.Store = activations.NewRedisStore(client, "", 0)
	for _, s := range sc.Setup {
		if s.Do == "fault" && s.Type == "activation_put_fails" {
			store = putFailsStore{store}
		}
	}

	e := &env{fs: fs, store: store, handles: map[string]string{},
		clock: func() time.Time { return time.Unix(1_700_000_000, 0).UTC() }}
	if sc.Config.Reconcile != nil {
		e.guardSec = sc.Config.Reconcile.ActivityGuardSeconds
	}
	e.eng = &engine.Engine{
		Cfg: cfg, Reg: registry.New(cfg), Provider: prov, Factory: fs,
		Messages: messages.New(messages.Templates{}), Clock: e.clock,
		Activations: store,
		OnEvent: func(_ context.Context, ev engine.QuotaEvent) {
			e.events = append(e.events, eventJSON{Kind: string(ev.Kind), Resource: ev.ResourceKey})
		},
	}

	ctx := context.Background()
	for _, s := range sc.Setup {
		switch s.Do {
		case "set_gauge":
			e.setGauge(t, s.Resource, s.Value)
		case "seed_open":
			opened := e.clock().Add(-time.Duration(s.AgeSeconds) * time.Second).Format(time.RFC3339)
			n := s.N
			if n == 0 {
				n = 1
			}
			for i := 0; i < n; i++ {
				if err := store.PutOpen(ctx, activations.Activation{
					ActivationID: fmt.Sprintf("act_seed_%s_%d", s.Resource, i),
					OrgID:        org, ResourceKey: s.Resource, State: "open",
					OpenedAt: opened, Spend: map[string]float64{s.Resource: 1},
				}); err != nil {
					t.Fatal(err)
				}
			}
		case "provider":
			observed := s.Observed
			e.provider = func(context.Context, string) (map[string]int, error) {
				return observed, nil
			}
		case "provider_unreachable":
			e.provider = func(context.Context, string) (map[string]int, error) {
				return nil, errors.New("injected: provider unreachable")
			}
		case "fault":
			// handled at store construction
		default:
			t.Fatalf("unknown setup do=%q", s.Do)
		}
	}
	return e
}

func (e *env) orgKey(rk string) string {
	return counters.Gauge{Prefix: e.fs.Prefix, ResourceKey: rk}.OrgKey(org)
}

func (e *env) setGauge(t *testing.T, rk string, v float64) {
	t.Helper()
	if err := e.fs.Floats.Set(context.Background(), e.orgKey(rk), v, 0); err != nil {
		t.Fatal(err)
	}
}

func (e *env) gauge(t *testing.T, key string) float64 {
	t.Helper()
	v, _, err := e.fs.Floats.GetFloat(context.Background(), key)
	if err != nil {
		t.Fatal(err)
	}
	return v
}

// ---------------------------------------------------------------------------
// gate + op execution (the Go half of the abstract-op mapping table; the
// Python half is generate_scenarios.py — keep the two in sync BY ROW)
// ---------------------------------------------------------------------------

// runGate returns the normalized admission outcome. An error at a gate is a
// NON-admission (fail-closed) — the fixture's documented mapping rule.
// Returns (admitted, supported).
func (e *env) runGate(gate string, sc scenarioJSON) (bool, bool) {
	ctx := context.Background()
	rk, bundle := "conf.g", "conf_bundle"
	if sc.Target != nil {
		if sc.Target.Resource != "" {
			rk = sc.Target.Resource
		}
		if sc.Target.Bundle != "" {
			bundle = sc.Target.Bundle
		}
	}
	switch gate {
	case "check_resource":
		res, err := e.eng.Check(ctx, engine.CheckInput{OrgID: org, ResourceKey: rk})
		if err != nil {
			return false, true
		}
		return res.Decision != engine.Deny, true
	case "check_bundle":
		return false, false // structural: Go has no bundle-check gate (SD-1)
	case "acquire_resource":
		res, err := e.eng.Acquire(ctx, engine.AcquireInput{OrgID: org, ResourceKey: rk})
		if err != nil {
			return false, true
		}
		return res.Admitted, true
	case "acquire_bundle":
		res, err := e.eng.Acquire(ctx, engine.AcquireInput{OrgID: org, BundleName: bundle})
		if err != nil {
			return false, true
		}
		return res.Admitted, true
	}
	return false, false
}

// runOp executes one op; any error normalizes to {"error": true}.
func (e *env) runOp(t *testing.T, op opJSON) map[string]any {
	ctx := context.Background()
	switch op.Op {
	case "acquire":
		in := engine.AcquireInput{OrgID: org, ResourceKey: op.Resource,
			BundleName: op.Bundle, UserID: op.User, IdempotencyKey: op.Idem}
		res, err := e.eng.Acquire(ctx, in)
		if err != nil {
			return map[string]any{"error": true}
		}
		if op.Save != "" {
			e.handles[op.Save] = res.ActivationID
		}
		return map[string]any{"admitted": res.Admitted,
			"minted": res.ActivationID != "", "reason": res.Reason}
	case "release_activation":
		id := op.ID
		if op.Ref != "" {
			id = e.handles[op.Ref]
		}
		performed, err := e.eng.ReleaseActivation(ctx, id)
		if err != nil {
			return map[string]any{"error": true}
		}
		return map[string]any{"performed": performed}
	case "settle":
		settled, err := e.eng.Settle(ctx, e.handles[op.Ref], op.Cost)
		if err != nil {
			return map[string]any{"error": true}
		}
		return map[string]any{"settled": settled}
	case "increment":
		v, err := e.eng.Spend(ctx, engine.CheckInput{OrgID: org,
			ResourceKey: op.Resource, Cost: op.Delta, UserID: op.User})
		if err != nil {
			return map[string]any{"error": true}
		}
		return map[string]any{"value": v}
	case "decrement":
		err := e.eng.Release(ctx, engine.CheckInput{OrgID: org,
			ResourceKey: op.Resource, Cost: op.Delta})
		if err != nil {
			return map[string]any{"error": true}
		}
		// Python decrement returns the new org value; Go Release does not —
		// normalize by reading the gauge.
		return map[string]any{"value": e.gauge(t, e.orgKey(op.Resource))}
	case "check":
		res, err := e.eng.Check(ctx, engine.CheckInput{OrgID: org, ResourceKey: op.Resource})
		if err != nil {
			return map[string]any{"error": true}
		}
		return map[string]any{"allowed": res.Decision != engine.Deny}
	case "get_gauge":
		g := counters.Gauge{Prefix: e.fs.Prefix, ResourceKey: op.Resource}
		switch op.Scope {
		case "", "org":
			return map[string]any{"value": e.gauge(t, g.OrgKey(org))}
		case "user":
			return map[string]any{"value": e.gauge(t, g.UserKey(org, op.User))}
		case "user_seq":
			return map[string]any{"value": e.gauge(t, g.UserSeqKey(org, op.User))}
		}
	case "set_gauge":
		e.setGauge(t, op.Resource, op.Value)
		return map[string]any{}
	case "concurrent_release":
		id := e.handles[op.Ref]
		var mu sync.Mutex
		performed := 0
		var wg sync.WaitGroup
		for i := 0; i < op.N; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				ok, err := e.eng.ReleaseActivation(ctx, id)
				if err != nil {
					t.Error(err)
					return
				}
				if ok {
					mu.Lock()
					performed++
					mu.Unlock()
				}
			}()
		}
		wg.Wait()
		return map[string]any{"performed_count": float64(performed)}
	case "reconcile_org":
		r := &reconcile.Reconciler{
			Store: durableStore{e.store}, Factory: e.fs, Reg: e.eng.Reg,
			Provider:        e.provider,
			RecentlyTouched: e.eng.TouchGuard(time.Duration(e.guardSec) * time.Second),
			Clock:           e.clock,
		}
		alerts, err := r.ReconcileOrg(ctx, org)
		if err != nil {
			return map[string]any{"error": true}
		}
		divergence, unreachable := false, false
		for _, a := range alerts {
			if a.Source == "provider" {
				divergence = true
			}
			if a.Source == "provider_unreachable" {
				unreachable = true
			}
		}
		return map[string]any{"divergence_alert": divergence, "unreachable_alert": unreachable}
	}
	t.Fatalf("unknown op %q", op.Op)
	return nil
}

// ---------------------------------------------------------------------------
// comparison
// ---------------------------------------------------------------------------

func toFloat(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case int:
		return float64(x), true
	}
	return 0, false
}

func compare(observed, expect map[string]any) []string {
	var diverged []string
	if b, _ := expect["error"].(bool); b {
		if ob, _ := observed["error"].(bool); !ob {
			diverged = append(diverged,
				fmt.Sprintf("fixture expects an ERROR, got %v", observed))
		}
		return diverged
	}
	if ob, _ := observed["error"].(bool); ob {
		return append(diverged, "unexpected ERROR")
	}
	for k, want := range expect {
		if k == "error" { // an explicit "error": false just means "no error required"
			continue
		}
		got, ok := observed[k]
		if !ok {
			diverged = append(diverged, fmt.Sprintf("%s: not observed (fixture=%v)", k, want))
			continue
		}
		if wf, wok := toFloat(want); wok {
			gf, gok := toFloat(got)
			if !gok || gf != wf {
				diverged = append(diverged, fmt.Sprintf("%s: observed=%v, fixture=%v", k, got, want))
			}
			continue
		}
		if got != want {
			diverged = append(diverged, fmt.Sprintf("%s: observed=%v, fixture=%v", k, got, want))
		}
	}
	return diverged
}

// expectFor picks the Go-side expectation: the recorded known-divergence
// override when present (D-54 pattern — documented, still machine-pinned),
// the shared expectation otherwise.
func expectFor(op opJSON) map[string]any {
	if op.ExpectGo != nil {
		return op.ExpectGo
	}
	return op.Expect
}

// ---------------------------------------------------------------------------
// the suite
// ---------------------------------------------------------------------------

func TestConformanceSuite_D43(t *testing.T) {
	fixture := loadFixture(t)
	if len(fixture.Scenarios) == 0 {
		t.Fatal("empty fixture")
	}
	for _, sc := range fixture.Scenarios {
		sc := sc
		t.Run(sc.ID, func(t *testing.T) {
			var diverged []string
			switch sc.Kind {
			case "gate_matrix":
				outcomes := map[string]bool{}
				for _, gate := range sc.Gates {
					env := newEnv(t, sc) // fresh state per gate (acquire spends)
					admitted, supported := env.runGate(gate, sc)
					if supported {
						outcomes[gate] = admitted
					}
				}
				if len(outcomes) == 0 {
					t.Fatalf("%s: runner executed NO gates — vacuous row", sc.ID)
				}
				agree := true
				var first bool
				for _, v := range outcomes {
					first = v
					break
				}
				for _, v := range outcomes {
					if v != first {
						agree = false
					}
				}
				if !agree {
					diverged = append(diverged,
						fmt.Sprintf("gates disagree (D-48 class): %v", outcomes))
				}
				rowExpect := sc.Expect
				if sc.ExpectGoRow != nil { // recorded known divergence (D-54 pattern)
					rowExpect = sc.ExpectGoRow
				}
				want, _ := rowExpect["admitted"].(bool)
				for gate, got := range outcomes {
					if got != want {
						diverged = append(diverged,
							fmt.Sprintf("gate %s: admitted=%v, fixture=%v", gate, got, want))
					}
				}
			case "sequence":
				env := newEnv(t, sc)
				for i, op := range sc.Ops {
					observed := env.runOp(t, op)
					for _, d := range compare(observed, expectFor(op)) {
						diverged = append(diverged,
							fmt.Sprintf("op[%d](%s).%s", i, op.Op, d))
					}
				}
				wantEvents := sc.ExpectEvents
				if sc.ExpectEventsGo != nil {
					wantEvents = *sc.ExpectEventsGo
				}
				if sc.ExpectEvents != nil || sc.ExpectEventsGo != nil {
					got, want := env.events, wantEvents
					if len(got) != len(want) {
						diverged = append(diverged,
							fmt.Sprintf("events: observed=%v, fixture=%v", got, want))
					} else {
						for i := range want {
							if got[i] != want[i] {
								diverged = append(diverged,
									fmt.Sprintf("events[%d]: observed=%v, fixture=%v", i, got[i], want[i]))
							}
						}
					}
				}
			default:
				t.Fatalf("unknown scenario kind %q", sc.Kind)
			}
			if len(diverged) > 0 {
				t.Errorf("RUNTIME DIVERGENCE (go) on %s %v:\n  %s",
					sc.ID, sc.DecisionRefs, join(diverged, "\n  "))
			}
		})
	}
}

func join(ss []string, sep string) string {
	out := ""
	for i, s := range ss {
		if i > 0 {
			out += sep
		}
		out += s
	}
	return out
}

// TestScenariosFileInSyncWithCanonical: the canonical fixture lives in the
// Python repo (the reference runtime generates it). When that path is visible
// (the shared dev box), a stale synced copy is a FAILURE, not a silent fork.
// Elsewhere (isolated CI), the check skips — the copy is then pinned by review.
func TestScenariosFileInSyncWithCanonical(t *testing.T) {
	canonical, err := os.ReadFile(canonicalPath)
	if err != nil {
		t.Skipf("canonical fixture not visible (%v) — sync is pinned by review here", err)
	}
	local, err := os.ReadFile("scenarios.json")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(canonical, local) {
		t.Fatal("scenarios.json is OUT OF SYNC with the canonical copy — run:\n" +
			"  cp " + canonicalPath + " ./scenarios.json")
	}
}

// TestKnownDivergenceRegisterIsDocumented: every recorded divergence must
// carry decision refs + a note — an undocumented divergence is a silent
// blessing (D-43/D-54).
func TestKnownDivergenceRegisterIsDocumented(t *testing.T) {
	fixture := loadFixture(t)
	for _, kd := range fixture.KnownDivergences {
		refs, _ := kd["decision_refs"].([]any)
		note, _ := kd["note"].(string)
		if len(refs) == 0 || note == "" {
			t.Errorf("known_divergence %v lacks decision_refs or note", kd["id"])
		}
	}
}
