// provision — T-2/T-3/T-4 (program board tooling lane; ticket
// 20260721_setup_and_doctor_verbs; ST-CLI-1). The missing VEHICLE: emit the
// infrastructure artifacts the boot gates enforce, generated FROM the
// enforcing registry so the artifact and the gate cannot drift.
//
// The verb is `provision`, NOT `setup` (ticket §6.1, DECIDED): quota.Setup is
// the library's own entry point and the collision would land in the docs.
//
// provision NEVER creates cloud resources — emit-and-let-them-apply (the D-3
// rule auto-create follows). `--local` creates ONE local Docker container,
// loudly, and only when asked.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ab0t-com/ab0t-quota-go/redisguard"
)

// requiredMaxmemoryPolicy is what the emitted artifacts configure. D-72's
// gate refuses every member of redisguard.EvictingPolicies; provisionSelfCheck
// proves this value is not one (and the ST-CLI-1 binding test proves the
// proof can go red).
var requiredMaxmemoryPolicy = "noeviction"

// requiredAppendonly — D-32/D-81: the outbox needs persistence, not just
// non-eviction.
var requiredAppendonly = "yes"

const (
	keyspacePattern    = "quota:*"
	defaultLocalPort   = 6399 // deliberately NOT 6379: declare, never discover
	localContainerName = "ab0t-quota-dev-redis"
)

// redisImage pins the major at (or above) the D-74 floor.
var redisImage = "redis:7-alpine"

var aclRequiredRules = []string{"+@read", "+@write", "+@scripting", "+ping"}
var aclOptionalRules = []string{"+info", "+config|get", "+cluster|info"}

var iamRuntimeActions = []string{
	"dynamodb:DescribeTable", "dynamodb:DescribeTimeToLive",
	"dynamodb:DescribeContinuousBackups",
	"dynamodb:GetItem", "dynamodb:PutItem", "dynamodb:UpdateItem",
	"dynamodb:DeleteItem", "dynamodb:Query", "dynamodb:Scan",
}
var iamCreateActions = []string{
	"dynamodb:CreateTable", "dynamodb:UpdateTimeToLive", "dynamodb:TagResource",
}

type gsiSpec struct {
	Name, HashKey, HashType, RangeKey, RangeType, Projection string
}

type tableSpec struct {
	CapKey      string
	DefaultName string
	TTLAttr     string
	GSIs        []gsiSpec
	Purpose     string
}

// tableSpecs mirrors the Python registry (ab0t_quota/provision.TABLE_SPECS)
// and the shared table contract both runtimes create/verify. ST-CLI-1's
// emit_must_contain pins the names cross-runtime.
var tableSpecs = []tableSpec{
	{"ddb_state", "ab0t_quota_state", "ttl",
		[]gsiSpec{{"GSI1", "GSI1PK", "S", "GSI1SK", "S", "ALL"}},
		"counter snapshots, org tiers, overrides"},
	{"ddb_outbox", "ab0t_quota_outbox", "ttl",
		[]gsiSpec{{"gsi_status", "gsi_status_pk", "S", "gsi_status_sk", "N", "ALL"}},
		"durable outbox — money lifecycle events nothing can reconstruct"},
	{"ddb_activations", "ab0t_quota_activations", "ttl",
		[]gsiSpec{{"GSI1", "GSI1PK", "S", "GSI1SK", "S", "ALL"}},
		"activation ledger — authoritative for identity + cost"},
	{"ddb_handler_ledger", "ab0t_quota_handler_ledger", "ttl",
		[]gsiSpec{{"gsi1", "gsi1_pk", "S", "gsi1_sk", "S", "ALL"},
			{"gsi2", "gsi2_pk", "S", "gsi2_sk", "S", "ALL"}},
		"idempotent-handler ledger (opt-in wiring)"},
}

// provisionSelfCheck — a provision that emits a policy the gates refuse is
// OUR bug (exit 4), never the consumer's.
func provisionSelfCheck() error {
	if redisguard.EvictingPolicies[requiredMaxmemoryPolicy] {
		return fmt.Errorf("provision registry emits maxmemory-policy=%s, which "+
			"the D-72 gate REFUSES", requiredMaxmemoryPolicy)
	}
	major, err := strconv.Atoi(strings.SplitN(strings.SplitN(redisImage, ":", 2)[1], "-", 2)[0])
	if err != nil || major < redisguard.VersionFloor[0] {
		return fmt.Errorf("provision registry pins image %s below the D-74 floor %d.%d.%d",
			redisImage, redisguard.VersionFloor[0], redisguard.VersionFloor[1], redisguard.VersionFloor[2])
	}
	return nil
}

func emitHeader(kind string) string {
	return fmt.Sprintf(`# GENERATED by 'quotactl provision --emit %s' — from the enforcing gate
# registry (D-71/72/73/74 Redis contract, D-76 tables). Regenerate rather than
# hand-edit; the gates and this artifact share one source.
# Contract: non-clustered Redis >= %d.%d.%d, maxmemory-policy %s, Lua
# scripting enabled; keyspace %s; four DynamoDB tables with GSIs, TTL
# attribute 'ttl', PITR.
`, kind, redisguard.VersionFloor[0], redisguard.VersionFloor[1], redisguard.VersionFloor[2],
		requiredMaxmemoryPolicy, keyspacePattern)
}

func emitCompose() string {
	return emitHeader("compose") + fmt.Sprintf(`services:
  quota-redis:
    image: %s
    container_name: %s
    # D-72 (never an evicting policy) + D-32/D-81 (outbox durability):
    command: ["redis-server", "--maxmemory-policy", "%s", "--appendonly", "%s"]
    ports:
      - "%d:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
  quota-dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

# DECLARE the stores (never discovered — the library reads no generic env var):
#   QUOTA_REDIS_URL=redis://localhost:%d/0
#   AB0T_QUOTA_DDB_PITR_CONFIRMED=true  # DynamoDB Local cannot report PITR
# Then verify: quotactl capabilities (runs Setup — its help text states the side effects)
`, redisImage, localContainerName, requiredMaxmemoryPolicy, requiredAppendonly,
		defaultLocalPort, defaultLocalPort)
}

func emitACL() string {
	return emitHeader("acl") + fmt.Sprintf(`# Minimal least-privilege user (Redis >= 6 ACL syntax). Replace CHANGE_ME.
ACL SETUSER ab0t-quota on >CHANGE_ME ~%s %s

# OPTIONAL — grants full machine-verification at boot/doctor. WITHOUT these
# the library cannot READ topology/policy/version and you must put the
# assertions on the record instead (storage.redis_cluster_confirmed_disabled,
# storage.redis_durability_confirmed):
#   ACL SETUSER ab0t-quota %s
`, keyspacePattern, strings.Join(aclRequiredRules, " "), strings.Join(aclOptionalRules, " "))
}

func emitTerraform() string {
	var b strings.Builder
	b.WriteString(emitHeader("terraform"))
	b.WriteString("# Emit-and-let-them-apply: this module CREATES NOTHING when printed — apply\n" +
		"# it with your own tooling and credentials (provision never touches your cloud).\n\n")
	for _, t := range tableSpecs {
		attrs := [][2]string{{"PK", "S"}, {"SK", "S"}}
		for _, g := range t.GSIs {
			attrs = append(attrs, [2]string{g.HashKey, g.HashType}, [2]string{g.RangeKey, g.RangeType})
		}
		fmt.Fprintf(&b, "# %s\nresource \"aws_dynamodb_table\" \"%s\" {\n", t.Purpose, t.CapKey)
		fmt.Fprintf(&b, "  name         = %q\n  billing_mode = \"PAY_PER_REQUEST\"\n", t.DefaultName)
		b.WriteString("  hash_key     = \"PK\"\n  range_key    = \"SK\"\n\n")
		for _, a := range attrs {
			fmt.Fprintf(&b, "  attribute {\n    name = %q\n    type = %q\n  }\n", a[0], a[1])
		}
		for _, g := range t.GSIs {
			fmt.Fprintf(&b, "  global_secondary_index {\n    name            = %q\n"+
				"    hash_key        = %q\n    range_key       = %q\n"+
				"    projection_type = %q\n  }\n", g.Name, g.HashKey, g.RangeKey, g.Projection)
		}
		fmt.Fprintf(&b, "  ttl {\n    attribute_name = %q\n    enabled        = true\n  }\n", t.TTLAttr)
		b.WriteString("  point_in_time_recovery {\n    enabled = true\n  }\n")
		b.WriteString("  server_side_encryption {\n    enabled = true\n  }\n")
		b.WriteString("  tags = {\n    Service   = \"ab0t-quota\"\n    ManagedBy = \"ab0t-quota-library\"\n  }\n}\n\n")
	}
	return b.String()
}

func emitIAM(includeCreate bool) string {
	var resources []string
	for _, t := range tableSpecs {
		base := "arn:aws:dynamodb:REGION:ACCOUNT:table/" + t.DefaultName
		resources = append(resources, base, base+"/index/*")
	}
	statements := []map[string]any{{
		"Sid": "Ab0tQuotaRuntime", "Effect": "Allow",
		"Action": iamRuntimeActions, "Resource": resources,
	}}
	note := "// Self-provisioning actions are NOT included — add them only with\n" +
		"// storage.auto_create_tables (re-run with --include-create).\n"
	if includeCreate {
		statements = append(statements, map[string]any{
			"Sid": "Ab0tQuotaSelfProvision", "Effect": "Allow",
			"Action": iamCreateActions, "Resource": resources,
		})
		note = ""
	}
	doc, _ := json.MarshalIndent(map[string]any{
		"Version": "2012-10-17", "Statement": statements}, "", "  ")
	return strings.ReplaceAll(emitHeader("iam"), "#", "//") + note + string(doc) + "\n"
}

// checkArtifactConformance verifies an emitted artifact against the SAME
// enforcing constants the gates read (D-14: the ST-CLI-1 binding test plants
// offenders and proves this can go RED). Token-level, like the Python twin.
func checkArtifactConformance(kind, text string) []string {
	var problems []string
	switch kind {
	case "compose":
		if !strings.Contains(text, requiredMaxmemoryPolicy) {
			problems = append(problems, "missing maxmemory-policy "+requiredMaxmemoryPolicy)
		}
		for p := range redisguard.EvictingPolicies {
			if strings.Contains(text, p) {
				problems = append(problems, "contains D-72-refused policy "+p)
			}
		}
		if !strings.Contains(text, "--appendonly") {
			problems = append(problems, "missing appendonly persistence (D-32/D-81)")
		}
	case "acl":
		if !strings.Contains(text, "~"+keyspacePattern) {
			problems = append(problems, "ACL not scoped to ~"+keyspacePattern)
		}
		for _, r := range aclRequiredRules {
			if !strings.Contains(text, r) {
				problems = append(problems, "ACL missing "+r)
			}
		}
		if strings.Contains(text, "+@all") || strings.Contains(text, "~* ") {
			problems = append(problems, "ACL is over-broad")
		}
	case "terraform", "iam":
		for _, t := range tableSpecs {
			if !strings.Contains(text, t.DefaultName) {
				problems = append(problems, "missing table "+t.DefaultName)
			}
		}
		if kind == "terraform" {
			for _, t := range tableSpecs {
				for _, g := range t.GSIs {
					if !strings.Contains(text, g.Name) {
						problems = append(problems, "missing GSI "+g.Name)
					}
				}
			}
			if !strings.Contains(text, "point_in_time_recovery") {
				problems = append(problems, "missing PITR block")
			}
		}
		if kind == "iam" {
			for _, a := range iamRuntimeActions {
				if !strings.Contains(text, a) {
					problems = append(problems, "missing IAM action "+a)
				}
			}
		}
	default:
		problems = append(problems, "unknown artifact kind "+kind)
	}
	return problems
}

func emitArtifact(kind string, includeCreate bool) (string, error) {
	if err := provisionSelfCheck(); err != nil {
		return "", err
	}
	var text string
	switch kind {
	case "compose":
		text = emitCompose()
	case "terraform":
		text = emitTerraform()
	case "acl":
		text = emitACL()
	case "iam":
		text = emitIAM(includeCreate)
	default:
		return "", fmt.Errorf("unknown --emit kind %q (compose|terraform|acl|iam)", kind)
	}
	if problems := checkArtifactConformance(kind, text); len(problems) > 0 {
		return "", fmt.Errorf("emitted %s artifact does not satisfy the enforcing "+
			"registry (a bug in quotactl, not your environment): %v", kind, problems)
	}
	return text, nil
}

func localDockerArgs(port int, name string) []string {
	return []string{"run", "-d", "--name", name,
		"-p", fmt.Sprintf("%d:6379", port), redisImage,
		"redis-server", "--maxmemory-policy", requiredMaxmemoryPolicy,
		"--appendonly", requiredAppendonly}
}

func newProvisionCmd() *cobra.Command {
	var emitKind string
	var includeCreate, local, dryRun bool
	var port int
	var name string
	cmd := &cobra.Command{
		Use:   "provision",
		Short: "Emit infra artifacts from the enforcing gate registry, or start a conforming local dev Redis",
		Long: `Emits compose|terraform|acl|iam artifacts satisfying the SAME contract the
boot gates enforce — generated from one registry, so artifact and gate cannot
drift. NEVER creates cloud resources: emit-and-let-them-apply.

--local starts ONE local Docker Redis conforming to the gates (side effect
stated: a docker container; nothing else, never cloud).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if local {
				argv := localDockerArgs(port, name)
				fmt.Fprintln(os.Stderr, "provision --local — side effect statement: this creates/starts "+
					"ONE local Docker container ("+name+"); it never touches cloud resources.")
				if dryRun {
					fmt.Fprintln(os.Stderr, "DRY RUN — would execute:\n  docker "+strings.Join(argv, " "))
					return nil
				}
				out, err := exec.Command("docker", argv...).CombinedOutput()
				if err != nil {
					fmt.Fprintf(os.Stderr, "docker failed: %v\n%s\nequivalent manual command:\n  docker %s\n",
						err, out, strings.Join(argv, " "))
					os.Exit(3)
				}
				fmt.Fprintf(os.Stderr, "started %s on localhost:%d\nDeclare it (never discovered):\n"+
					"  QUOTA_REDIS_URL=redis://localhost:%d/0\n"+
					"Then verify: quotactl capabilities\n", name, port, port)
				return nil
			}
			if emitKind == "" {
				return errors.New("choose --emit {compose|terraform|acl|iam} or --local")
			}
			text, err := emitArtifact(emitKind, includeCreate)
			if err != nil {
				fmt.Fprintln(os.Stderr, "provision internal error:", err)
				os.Exit(4)
			}
			fmt.Print(text)
			return nil
		},
	}
	cmd.Flags().StringVar(&emitKind, "emit", "", "artifact to print (compose|terraform|acl|iam)")
	cmd.Flags().BoolVar(&includeCreate, "include-create", false,
		"(--emit iam) include self-provisioning actions — only with auto table creation")
	cmd.Flags().BoolVar(&local, "local", false, "start ONE conforming local Docker Redis")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "print the docker command, run nothing")
	cmd.Flags().IntVar(&port, "port", defaultLocalPort,
		"host port for --local (deliberately not 6379: declare, never discover)")
	cmd.Flags().StringVar(&name, "name", localContainerName, "container name for --local")
	return cmd
}
